[package]
name = "pronk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "pronkd"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
nix.workspace = true
pronk-backend-host = { path = "../pronk-backend-host" }
pronk-backend-protocol = { path = "../pronk-backend-protocol" }
pronk-core = { path = "../pronk-core" }
pronk-dbus = { path = "../pronk-dbus" }
pronk-pipewire = { path = "../pronk-pipewire" }
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zbus.workspace = true
zvariant.workspace = true

[dev-dependencies]
async-trait.workspace = true
castkms-sys = { path = "../castkms-sys" }
futures-util.workspace = true

[lints]
workspace = true
