[package]
name = "pronk-gpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
vulkan = ["dep:ash"]

[dependencies]
ash = { version = "=0.38.0", optional = true }
nix.workspace = true
pronk-dmabuf = { path = "../pronk-dmabuf" }

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
