[package]
name = "castkms-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
castkms-sys = { path = "../castkms-sys" }
drm-display-executor = { path = "../drm-display-executor" }
nix.workspace = true
pronk-gpu = { path = "../pronk-gpu", features = ["vulkan"] }

[lints]
workspace = true
