[package]
name = "pronk-capture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
drm-capture = { path = "../drm-capture" }
pronk-dmabuf = { path = "../pronk-dmabuf" }
nix.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
