[package]
name = "pronk-renderer-pipewire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
castkms-renderer = { path = "../castkms-renderer" }
pronk-pipewire = { path = "../pronk-pipewire" }
pronk-gpu = { path = "../pronk-gpu", features = ["vulkan"] }
pronk-renderer-worker = { path = "../pronk-renderer-worker" }
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
