[package]
name = "pronkctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
pronk-dbus = { path = "../pronk-dbus" }
tokio.workspace = true
zbus.workspace = true

[lints]
workspace = true
