[package]
name = "pronk-backend-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
nix.workspace = true
pronk-backend-protocol = { path = "../pronk-backend-protocol" }
pronk-userns = { path = "../pronk-userns" }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
zbus.workspace = true

[lints]
workspace = true
