[package]
name = "pronk-capture-broker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
castkms-renderer = { path = "../castkms-renderer" }
drm-capture = { path = "../drm-capture" }
nix.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
zbus.workspace = true

[lints]
workspace = true
