[package]
name = "pronk-systemd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nix.workspace = true
sd-notify.workspace = true
thiserror.workspace = true
zbus.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
